"""FinanceRAG — Streamlit interface.

Ask a financial question, pick a dataset, and get an LLM-generated answer
grounded in the top retrieved passages (with citations). Falls back to a pure
retrieval view when no OpenAI key is configured.

Run:
    streamlit run app/streamlit_app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

# Make the repo root importable when run via `streamlit run app/streamlit_app.py`.
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from financerag_app.config import DATASET_INFO, DATASETS, AppConfig, get_dataset_config  # noqa: E402
from financerag_app.data import dataset_available  # noqa: E402
from financerag_app.pipeline import RAGPipeline  # noqa: E402

st.set_page_config(page_title="FinanceRAG", page_icon="💹", layout="wide")


@st.cache_resource(show_spinner=False)
def get_pipeline() -> RAGPipeline:
    """One pipeline (and one set of loaded models) per server process."""
    return RAGPipeline(AppConfig())


@st.cache_resource(show_spinner="Building index (first time only)…")
def ensure_index(_pipe: RAGPipeline, dataset: str, model_tag: str):
    """Build+load a dataset index once. ``model_tag`` keys the cache."""
    _pipe.load_dataset(dataset)
    return True


def sidebar(cfg: AppConfig):
    st.sidebar.title("💹 FinanceRAG")
    st.sidebar.caption("Hybrid retrieval → rerank → grounded answer")

    labels = {d: DATASET_INFO.get(d, {}).get("label", d) for d in DATASETS}
    available = [d for d in DATASETS if dataset_available(d, cfg.data_dir)[0]]
    if not available:
        st.sidebar.error("No datasets found under the data/ directory.")
        st.stop()

    dataset = st.sidebar.selectbox(
        "Dataset",
        available,
        format_func=lambda d: labels[d],
    )
    st.sidebar.caption(DATASET_INFO.get(dataset, {}).get("desc", ""))

    st.sidebar.divider()
    st.sidebar.subheader("Settings")
    top_k = st.sidebar.slider("Passages to retrieve", 3, 20, cfg.top_k_final)

    dc = get_dataset_config(dataset)
    alpha = st.sidebar.slider(
        "Hybrid α (dense ↔ BM25)", 0.0, 1.0, float(dc.hybrid_alpha), 0.05,
        help="1.0 = pure semantic/dense, 0.0 = pure keyword/BM25.",
    )
    use_reranker = st.sidebar.checkbox("Use cross-encoder reranker", value=cfg.use_reranker)

    st.sidebar.divider()
    if cfg.openai_api_key:
        generate = st.sidebar.checkbox("Generate AI answer", value=cfg.use_generation)
        st.sidebar.success(f"LLM: {cfg.llm_model}")
    else:
        generate = False
        st.sidebar.warning("No OPENAI_API_KEY — retrieval-only mode. Set the key to enable answers.")

    st.sidebar.divider()
    st.sidebar.caption(f"Embedding: `{Path(cfg.embedding_model).name}`")
    st.sidebar.caption(f"Reranker: `{Path(cfg.reranker_model).name}`")
    return dataset, top_k, alpha, use_reranker, generate


def render_answer(result):
    gen = result.generation
    st.subheader("Answer")
    if gen and gen.used and result.answer:
        st.markdown(result.answer)
        st.caption(f"Generated by {gen.model} · grounded in {len(result.passages)} passages")
    elif gen and gen.error:
        st.info(gen.error)
    else:
        st.info("Retrieval-only mode — see the passages below.")


def render_passages(result):
    st.subheader(f"Retrieved passages ({len(result.passages)})")
    for p in result.passages:
        title = f"**[{p.rank}]** `{p.doc_id}`"
        if p.title:
            title += f" — {p.title}"
        title += f"  ·  score {p.score:.3f}"
        with st.expander(title, expanded=p.rank <= 3):
            st.text(p.snippet)


def main():
    cfg = AppConfig()
    pipe = get_pipeline()
    dataset, top_k, alpha, use_reranker, generate = sidebar(cfg)

    # Apply UI overrides to the shared config.
    cfg.use_reranker = use_reranker
    pipe.cfg.use_reranker = use_reranker

    st.title("Ask a financial question")
    st.caption(
        f"Searching **{DATASET_INFO.get(dataset, {}).get('label', dataset)}** — "
        f"{DATASET_INFO.get(dataset, {}).get('desc', '')}"
    )

    question = st.text_input(
        "Question",
        placeholder="e.g. What was Apple's total net sales in 2022?",
        label_visibility="collapsed",
    )
    ask = st.button("Search", type="primary")

    if ask and question.strip():
        model_tag = Path(cfg.embedding_model).name
        try:
            ensure_index(pipe, dataset, model_tag)
        except Exception as exc:
            st.error(f"Failed to build index for {dataset}: {exc}")
            st.stop()

        with st.spinner("Retrieving and reasoning…"):
            try:
                result = pipe.query(
                    dataset, question.strip(), top_k=top_k, alpha=alpha, generate=generate
                )
            except Exception as exc:
                st.error(f"Query failed: {exc}")
                st.stop()

        render_answer(result)
        st.divider()
        render_passages(result)

        with st.expander("⏱ Timings"):
            st.json(result.timings)
    elif ask:
        st.warning("Please type a question first.")


if __name__ == "__main__":
    main()
